
#include "nsISupports.idl"

[scriptable, uuid(4073f0b0-665c-11e1-b86c-0800200c9a66)]
interface nsIFireClosureUtils : nsISupports {

    [implicit_jscontext] jsval getParentScope(in jsval obj);
    [implicit_jscontext] jsval getScope(in jsval obj);

};
